image: docker/compose:latest

# ### Define variables
#
variables:
  # 1) Name of directory where restore and build objects are stored.
  OBJECTS_DIRECTORY: 'obj'
  # 2) Name of directory used for keeping restored dependencies.
  NUGET_PACKAGES_DIRECTORY: '.nuget'

stages:
  - build
  - test
  - deploy

services:
  - docker:dind

before_script:
  - docker info
  - docker-compose version

build:
  stage: build
  script:
    - docker-compose build

deploy:
  stage: deploy
  script:
    - 'export SHARED_VOLUME_DIR="$(dirname ${CI_PROJECT_DIR})/shared"'
    - mkdir -p ${SHARED_VOLUME_DIR}
    - docker-compose up -d
    - docker-compose ps
