image: docker/compose:1.27.4

### Define variables
variables:
  E2E_PROJECT_NAME: e2e-test
  DEFAULT_PROJECT_NAME: ex-5-amqp

stages:
  - build
  - test
  - deploy

services:
  - docker:dind

before_script:
  - docker info
  - docker-compose version

build:
  stage: build
  script:
    - docker-compose --project-name $E2E_PROJECT_NAME build
    - docker-compose --project-name $DEFAULT_PROJECT_NAME build

test:
  stage: test
  variables:
    # Exclude E2E tests
    TEST_FILTER: "FullyQualifiedName!~E2E"
    ENV_FILE: ".env.test"
  script:
    - ./DevOps/scripts/create-test-env-file.sh ${ENV_FILE}
    - ./DevOps/scripts/run-docker-tests.sh ./Dockerfile . ${ENV_FILE} ./unittests
  artifacts:
    when: always
    paths:
      - ./unittests/**/*.xml
    reports:
      junit:
        - ./unittests/**/*.xml

e2e:
  stage: test

  variables:
    RABBITMQ_DEFAULT_USER: rabbit_user
    RABBITMQ_DEFAULT_PASS: rabbit_pass
    RABBITMQ_PUBLIC_PORT: 5777
    RABBITMQ_MANAGEMENT_PUBLIC_PORT: 15677
    HTTP_SERVER_PORT: 9512
    HttpServerUrl: "http://httpserver"
    # Include only E2E tests
    TEST_FILTER: "FullyQualifiedName~E2E"
    ENV_FILE: ".env.e2e"
    E2E: "true"

  script:
    - ./DevOps/scripts/create-test-env-file.sh ${ENV_FILE}
    - docker-compose --project-name $E2E_PROJECT_NAME down
    - docker-compose --project-name $E2E_PROJECT_NAME up -d
    - docker-compose --project-name $E2E_PROJECT_NAME ps
    - 'export EXTRA_RUN_ARGS="--network ${E2E_PROJECT_NAME}_backend"'
    - ./DevOps/scripts/run-docker-tests.sh ./Dockerfile . ${ENV_FILE} ./testresults

  after_script:
    - docker-compose --project-name $E2E_PROJECT_NAME logs --tail="all" original
    - docker-compose --project-name $E2E_PROJECT_NAME logs --tail="all" observer
    - docker-compose --project-name $E2E_PROJECT_NAME logs --tail="all" httpserver
    - docker-compose --project-name $E2E_PROJECT_NAME down

  artifacts:
    when: always
    paths:
      - ./testresults/**/*.xml
    reports:
      junit:
        - ./testresults/**/*.xml

deploy:
  stage: deploy
  script:
    # Ensure we re-start the containers
    - docker-compose --project-name $DEFAULT_PROJECT_NAME down
    - docker-compose --project-name $DEFAULT_PROJECT_NAME up -d
    - docker-compose --project-name $DEFAULT_PROJECT_NAME ps


