image: docker/compose:1.27.4

### Define variables
variables:
  HTTP_SERVER_PORT: 8080

stages:
  - build
  - test
  - deploy

services:
  - docker:dind

before_script:
  - docker info
  - docker-compose version

build:
  stage: build
  script:
    - docker-compose build

test:
  stage: test
  script:
    - echo "Tests will be run once they are implemented..."

deploy:
  stage: deploy
  script:
    # Ensure we re-start the containers
    - docker-compose up -d --force-recreate
    - docker-compose ps
