image: docker/compose:latest

### Define variables
variables:
  # The default config has the gitlab running in port 8080
  # so this overrides the port when running the application
  HTTP_SERVER_PORT: 8082

stages:
  - build
  - test
  - deploy

services:
  - docker:dind

before_script:
  - docker info
  - docker-compose version

build:
  stage: build
  script:
    - docker-compose build

test:
  stage: test
  script:
    - echo "Tests will be run once they are implemented..."

deploy:
  stage: deploy
  script:
    # Ensure we re-start the containers
    # - docker-compose down
    - docker-compose up -d --force-recreate
    - docker-compose ps
