image: docker/compose:1.27.4

### Define variables
variables:
  HTTP_SERVER_PORT: 8080

stages:
  - build
  - test
  - deploy

services:
  - docker:dind

before_script:
  - docker info
  - docker-compose version
  - ls -la ./DevOps/scripts
  # - docker run --name debpwsh --rm mcr.microsoft.com/powershell:7.1.0-debian-buster-slim pwsh -Version

build:
  stage: build
  script:
    - docker-compose build

test:
  stage: test
  script:
    - echo "Tests will be run once they are implemented..."

e2e:
  stage: test
  script:
    - 'export NAME_PREFIX=e2e-test'
    - ./DevOps/scripts/run-docker-tests.sh ./Dockerfile .
    - echo "E2E tests will be run once they are implemented..."

deploy:
  stage: deploy
  script:
    # Ensure we re-start the containers
    - docker-compose up -d --force-recreate
    - docker-compose ps
