version: "3.4"

# Utilize extension fields https://docs.docker.com/compose/compose-file/#extension-fields
# To pass through common environment variables to containers
x-common-env-config: &common-env-config
  RabbitMQ__Host:
  RabbitMQ__Port:
  RabbitMQ__Username: ${RabbitMQ__Username:-rabbit_user}
  RabbitMQ__Password: ${RabbitMQ__Password:-rabbit_pass}

x-common-service-properties: &common-service-properties
  command: ["./wait-for-tcp.sh", "${RabbitMQ__Host:-rabbitmq}", "${RabbitMQ__Port:-5672}", "--", "./entry.sh"]

services:
  original:
    hostname: original
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - TargetProject=Original

    << : *common-service-properties

    environment:
      << : *common-env-config
      OutFilePath: /app/shared_volume/message.txt

    networks:
      - backend

  intermediate:
    hostname: intermediate
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - TargetProject=Intermediate

    << : *common-service-properties

    environment: *common-env-config

    networks:
      - backend

  observer:
    hostname: observer
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - TargetProject=Observer

    << : *common-service-properties

    networks:
      - backend

    environment:
      << : *common-env-config
      OutFilePath: /app/shared_volume/message.txt

    volumes:
      - shared:/app/shared_volume

  httpserver:
    hostname: httpserver
    ports:
        - "${HTTP_SERVER_PORT:-8080}:80"
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - TargetProject=HttpServer

    environment:
      << : *common-env-config
      OutFilePath: /app/shared_volume/message.txt

    volumes:
      - shared:/app/shared_volume

    networks:
      - backend

  rabbitmq:
    restart: unless-stopped
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      # The standard AMQP protocol port
      - '${RABBITMQ_PUBLIC_PORT:-5672}:5672'
      # HTTP management UI
      - '${RABBITMQ_MANAGEMENT_PUBLIC_PORT:-15672}:15672'

    # Uncomment to disable rabbitmq logging
    # logging:
    #     driver: none

    environment:
      RABBITMQ_DEFAULT_USER: ${RabbitMQ__Username:-rabbit_user}
      RABBITMQ_DEFAULT_PASS: ${RabbitMQ__Password:-rabbit_pass}

    networks:
      - backend

networks:
    backend: {}

volumes:
    shared: {}
