version: "3.4"

# Utilize extension fields https://docs.docker.com/compose/compose-file/#extension-fields
# To pass through common environment variables to containers
x-common-env-config: &common-env-config
  RabbitMQ__Host:
  RabbitMQ__Port:
  RabbitMQ__Username: ${RabbitMQ__Username:-rabbit_user}
  RabbitMQ__Password: ${RabbitMQ__Password:-rabbit_pass}

services:
  original:
    hostname: original
    container_name: ${NAME_PREFIX:-ex-5-amqp}-original
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - TargetProject=Original

    environment:
      << : *common-env-config
      OutFilePath: /app/shared_volume/message.txt

    networks:
      - backend

  intermediate:
    hostname: intermediate
    container_name: ${NAME_PREFIX:-ex-5-amqp}-intermediate
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - TargetProject=Intermediate

    environment: *common-env-config

    networks:
      - backend

  observer:
    hostname: observer
    container_name: ${NAME_PREFIX:-ex-5-amqp}-observer
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - TargetProject=Observer

    networks:
      - backend

    environment:
      << : *common-env-config
      OutFilePath: /app/shared_volume/message.txt

    volumes:
      - shared:/app/shared_volume

  httpserver:
    hostname: httpserver
    container_name: ${NAME_PREFIX:-ex-5-amqp}-httpserver
    ports:
        - "${HTTP_SERVER_PORT:-8080}:80"
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - TargetProject=HttpServer

    environment:
      << : *common-env-config
      OutFilePath: /app/shared_volume/message.txt

    volumes:
      - shared:/app/shared_volume

    networks:
      - backend

  rabbitmq:
    restart: unless-stopped
    image: rabbitmq:3-management
    container_name: ${NAME_PREFIX:-ex-5-amqp}-rabbitmq
    hostname: rabbitmq
    ports:
      # The standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'

    # Uncomment to disable rabbitmq logging
    # logging:
    #     driver: none

    environment:
      RABBITMQ_DEFAULT_USER: ${RabbitMQ__Username:-rabbit_user}
      RABBITMQ_DEFAULT_PASS: ${RabbitMQ__Password:-rabbit_pass}

    networks:
      - backend

networks:
    backend: {}

volumes:
    shared: {}
