version: "3"

services:
  original:
    hostname: original
    container_name: ex-5-amqp-original
    build:
      context: ./src
      dockerfile: ./Original/Dockerfile

    networks:
      - backend

  intermediate:
    hostname: intermediate
    container_name: ex-5-amqp-intermediate
    build:
      context: ./src
      dockerfile: ./Intermediate/Dockerfile

    networks:
      - backend

  observer:
    hostname: observer
    container_name: ex-5-amqp-observer
    build:
      context: ./src
      dockerfile: ./Observer/Dockerfile

    networks:
      - backend

    environment:
      - OutFilePath=/app/shared_volume/message.txt

    volumes:
      - shared:/app/shared_volume

  httpserver:
    hostname: httpserver
    container_name: ex-5-amqp-httpserver
    ports:
        - "${HTTP_SERVER_PORT:-8080}:80"
    build:
      context: ./src
      dockerfile: ./HttpServer/Dockerfile

    environment:
      - OutFilePath=/app/shared_volume/message.txt

    volumes:
      - shared:/app/shared_volume

    networks:
      - backend

  rabbitmq:
    restart: unless-stopped
    image: rabbitmq:3-management
    container_name: ex-5-amqp-rabbitmq
    hostname: rabbitmq
    ports:
      # The standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'

    # Uncomment to disable rabbitmq logging
    # logging:
    #     driver: none

    environment:
      RABBITMQ_DEFAULT_USER: "rabbit_user"
      RABBITMQ_DEFAULT_PASS: "rabbit_pass"

    networks:
      - backend

networks:
    backend: {}

volumes:
    shared: {}
